// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTqPKLLWd0Oh9MUWPxbvltsYVVgj1CnI',
    appId: '1:405204862515:web:92516f44217fd8a5fdc546',
    messagingSenderId: '405204862515',
    projectId: 'stream-eaa99',
    authDomain: 'stream-eaa99.firebaseapp.com',
    storageBucket: 'stream-eaa99.appspot.com',
    measurementId: 'G-HM8PTD3WQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXI9vukd5QdhAKPpzPt5PaP172T1jyMD8',
    appId: '1:405204862515:android:bbb321587d7b3ab2fdc546',
    messagingSenderId: '405204862515',
    projectId: 'stream-eaa99',
    storageBucket: 'stream-eaa99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6xOrvgvanX0uGX0B3gTmkQCTS3ty53s',
    appId: '1:405204862515:ios:df2c5db8c4d32512fdc546',
    messagingSenderId: '405204862515',
    projectId: 'stream-eaa99',
    storageBucket: 'stream-eaa99.appspot.com',
    iosClientId: '405204862515-1bcu79fd8ssr6svb8ubofj57vvtic2b6.apps.googleusercontent.com',
    iosBundleId: 'app.kiishidart.stream',
  );
}
